services:

  logstash:
    image: courselabs/logstash:7.10
    volumes:
      - ./data:/data
      - ./pipelines:/pipelines
      - ./config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    networks:
      - elkstack

networks:
  elkstack:
