services:

  elasticsearch:
    image: courselabs/elasticsearch:7.10
    ports: 
      - 9200:9200
    networks:
      - elkstack

  kibana:
    image: courselabs/kibana:7.10
    ports: 
      - 5601:5601
    networks:
      - elkstack
      
networks:
  elkstack:
