services:

  elasticsearch:
    image: courselabs/elasticsearch:7.10
    build: 
      context: ./elasticsearch
      args: 
        - ES_VERSION=7.10.2

  kibana:
    image: courselabs/kibana:7.10
    build: 
      context: ./kibana
      args: 
        - KIBANA_VERSION=7.10.2
        - NODE_TAG=10.23.1-alpine3.11

#  data-brfss:
#    image: courselabs/elasticsearch-data:brfss
#    build: 
#      context: ./elasticsearch-data-brfss

  python-elasticsearch:
    image: courselabs/python-elasticsearch:7.10
    build: 
      context: ./python-elasticsearch

