services:

  elasticsearch:
    image: courselabs/elasticsearch:7.10
    build: 
      context: ./elasticsearch
      args: 
        - ES_VERSION=7.10.2

  kibana:
    image: courselabs/kibana:7.10
    build: 
      context: ./kibana
      args: 
        - KIBANA_VERSION=7.10.2
        - NODE_TAG=10.23.1-alpine3.11

